name: Build, test and upload .pkg to S3

# The scheduler runs at 9 am UTC every day.
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
  schedule:
    - cron: '0 9 * * *'
env:
  GO111MODULE: on

permissions:
  # This is required for configure-aws-credentials to request an OIDC JWT ID token to access AWS resources later on.
  # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
  get-tag-name:
    name: Get tag name
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Check tag from workflow input and github ref
        id: check-tag
        run: |
          if [ -n "${{ inputs.ref_name }}" ]; then
            tag=${{ inputs.ref_name }}
          else
            tag=${{ github.ref_name }}
          fi
          echo "tag=$tag" >> ${GITHUB_OUTPUT}

  macos-aarch64-pkg-build:
    needs: get-tag-name
    uses: ./.github/workflows/build-pkg.yaml
    with:
      os: macos
      arch: arm64
      version: 14
      tag: ${{ needs.get-tag-name.outputs.tag }}

  macos-x86-64-pkg-build:
    needs: get-tag-name
    uses: ./.github/workflows/build-pkg.yaml
    with:
      os: macos
      arch: amd64
      version: 14
      tag: ${{ needs.get-tag-name.outputs.tag }}

  macos-aarch64-pkg-test:
    strategy:
      fail-fast: false
      matrix:
        version: [11, 13, 14]
    needs:
      - get-tag-name
      - macos-aarch64-pkg-build
    uses: ./.github/workflows/test-pkg.yaml
    with:
      os: macos
      arch: arm64
      version: ${{ matrix.version }}
      tag: ${{ needs.get-tag-name.outputs.tag }}

  macos-x86-64-pkg-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos]
        version: [11, 13, 14]
        arch: [amd64, arm64]
    needs:
      - get-tag-name
      - macos-aarch64-pkg-build
    uses: ./.github/workflows/test-pkg.yaml
    with:
      os: macos
      arch: amd64
      version: ${{ matrix.version }}
      tag: ${{ needs.get-tag-name.outputs.tag }}
